import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  BrainCircuit, Sparkles, FileText, BarChart3, ArrowRight,
  Briefcase, Mic, Radio, Volume2, Cpu,
} from 'lucide-react';
import { useAuthStore } from '@/store/authStore';
import { ThemeToggle } from '@/components/common';
import AiVoiceInterviewShowcase from '@/components/home/AiVoiceInterviewShowcase';

const FEATURES = [
  {
    icon: Mic,
    title: '3D AI Voice Interviewer',
    desc: 'Practice spoken technical interviews with realistic neural speech synthesis, live mic recognition, and real-time audio reactions.',
    color: 'from-cyan-600 to-blue-600',
  },
  {
    icon: FileText,
    title: 'Resume-Aware Questions',
    desc: 'Upload your resume and get interview questions tailored to your actual experience, projects, and verified tech stack.',
    color: 'from-brand-600 to-violet-600',
  },
  {
    icon: BrainCircuit,
    title: 'AI-Powered Question Engine',
    desc: 'Questions generated by Llama-3 via Groq — covering deep technical, distributed system design, situational & behavioral formats.',
    color: 'from-emerald-600 to-teal-600',
  },
  {
    icon: BarChart3,
    title: 'Instant Feedback & Scores',
    desc: 'Get detailed AI feedback, ATS keyword match scores, and a question-by-question performance analysis after every answer.',
    color: 'from-amber-600 to-orange-600',
  },
];

const STEPS = [
  { step: '01', title: 'Create Account', desc: 'Sign up in seconds — no credit card required.' },
  { step: '02', title: 'Set Up Interview', desc: 'Enter the job description, select experience level & question types.' },
  { step: '03', title: 'Practice & Improve', desc: 'Answer questions and get AI-powered feedback instantly.' },
];

export default function LandingPage() {
  const { isAuthenticated } = useAuthStore();

  return (
    <div className="min-h-screen bg-surface overflow-x-hidden">
      {/* ── Navbar ──────────────────────────────────────────────── */}
      <nav className="fixed top-0 w-full z-50 bg-surface/80 backdrop-blur-md border-b border-surface-border">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-1.5 bg-gradient-brand rounded-lg shadow-brand">
              <BrainCircuit className="w-5 h-5 text-white" />
            </div>
            <span className="font-display font-bold text-lg gradient-text">InterviewAI</span>
          </div>

          {/* Desktop Nav Links */}
          <div className="hidden md:flex items-center gap-8">
            <Link to="/jobs" className="text-sm font-medium text-slate-400 hover:text-white transition-colors flex items-center gap-2">
              <Briefcase className="w-4 h-4" />
              Jobs
              <span className="text-[10px] bg-brand-600/20 text-brand-400 px-1.5 py-0.5 rounded border border-brand-500/20 font-bold uppercase tracking-tight">
                Soon
              </span>
            </Link>
          </div>

          <div className="flex items-center gap-3">
            {isAuthenticated ? (
              <Link to="/dashboard" className="btn-primary">Go to Dashboard</Link>
            ) : (
              <>
                <Link to="/login" className="btn-ghost">Sign In</Link>
                <Link to="/register" className="btn-primary">Get Started Free</Link>
              </>
            )}
            <ThemeToggle />
          </div>
        </div>
      </nav>

      {/* ── Hero ─────────────────────────────────────────────────── */}
      <section className="relative pt-28 pb-20 px-6 overflow-hidden">
        {/* Glowing ambient light orbs */}
        <div className="absolute top-16 left-1/2 -translate-x-1/2 w-[700px] h-[450px] bg-brand-600/20 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-36 right-1/4 w-80 h-80 bg-violet-600/15 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-64 left-1/4 w-72 h-72 bg-cyan-500/15 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-6xl mx-auto text-center relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7 }}
          >
            <span className="badge-brand badge mb-6 inline-flex items-center gap-2 px-3 py-1">
              <Sparkles className="w-3.5 h-3.5 text-brand-400" />
              Interactive 3D Simulation • Real-Time Voice Intelligence
            </span>

            <h1 className="text-5xl sm:text-6xl lg:text-7xl font-display font-bold text-white leading-tight mb-6">
              Practice Today,<br />
              <span className="gradient-text">Get Hired Tomorrow</span>
            </h1>

            <p className="text-lg sm:text-xl text-slate-400 max-w-2xl mx-auto mb-8 leading-relaxed">
              Upload your resume, paste a job description, and practice with our {' '}
              <strong className="text-white">3D AI Voice Interviewer</strong> featuring speech synthesis, live mic recognition, and real-time ATS feedback.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-6">
              <Link to="/register" className="btn-primary text-base px-8 py-4 shadow-lg shadow-brand-500/25">
                Start Practicing Free <ArrowRight className="w-5 h-5" />
              </Link>
              <a
                href="#interactive-demo"
                className="btn-secondary text-base px-8 py-4 flex items-center gap-2"
              >
                <Radio className="w-4 h-4 text-cyan-400 animate-pulse" /> Try Voice Assistant Demo
              </a>
            </div>

            <p className="text-slate-500 text-xs mb-10">
              No credit card required • WebGL 3D Interactive • Works on all modern browsers
            </p>

            {/* ── 3D AI Interview & Voice Assistant Showcase ── */}
            <div id="interactive-demo" className="pt-2">
              <AiVoiceInterviewShowcase />
            </div>
          </motion.div>
        </div>
      </section>

      {/* ── Features ─────────────────────────────────────────────── */}
      <section className="py-20 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-display font-bold text-white mb-4">
              Everything you need to <span className="gradient-text">prepare</span>
            </h2>
            <p className="text-slate-400 max-w-xl mx-auto">
              A complete AI interview prep platform with interactive 3D simulations and conversational intelligence.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map(({ icon: Icon, title, desc, color }, i) => (
              <motion.div
                key={title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="card-hover p-6 group flex flex-col justify-between"
              >
                <div>
                  <div className={`w-12 h-12 rounded-2xl bg-gradient-to-br ${color} flex items-center justify-center mb-5 shadow-card group-hover:shadow-glow transition-shadow`}>
                    <Icon className="w-6 h-6 text-white" />
                  </div>
                  <h3 className="text-base font-semibold text-white mb-2">{title}</h3>
                  <p className="text-slate-400 text-xs leading-relaxed">{desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How It Works ─────────────────────────────────────────── */}
      <section className="py-20 px-6 bg-surface-card border-y border-surface-border">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-display font-bold text-white mb-4">
              From zero to <span className="gradient-text">interview-ready</span>
            </h2>
            <p className="text-slate-400">Three simple steps to supercharge your practice</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {STEPS.map(({ step, title, desc }, i) => (
              <motion.div key={step}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.15 }}
                className="text-center"
              >
                <div className="w-14 h-14 bg-gradient-brand rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-brand">
                  <span className="text-white font-display font-bold text-lg">{step}</span>
                </div>
                <h3 className="text-lg font-semibold text-white mb-2">{title}</h3>
                <p className="text-slate-400 text-sm leading-relaxed">{desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ──────────────────────────────────────────────────── */}
      <section className="py-24 px-6 text-center">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="max-w-2xl mx-auto"
        >
          <h2 className="text-4xl font-display font-bold text-white mb-4">
            Ready to nail your next interview?
          </h2>
          <p className="text-slate-400 mb-8">
            Join thousands of candidates using AI to prepare smarter, not harder.
          </p>
          <Link to="/register" className="btn-primary text-base px-10 py-4 inline-flex">
            Get Started — It&apos;s Free <ArrowRight className="w-5 h-5" />
          </Link>
        </motion.div>
      </section>

      {/* ── Footer ───────────────────────────────────────────────── */}
      <footer className="border-t border-surface-border py-8 px-6">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <BrainCircuit className="w-5 h-5 text-brand-400" />
            <span className="font-display font-semibold text-white">InterviewAI</span>
          </div>
          <p className="text-slate-500 text-sm">© 2026 InterviewAI. Built with MERN + Groq AI.</p>
        </div>
      </footer>
    </div>
  );
}
